# Generated by Django 5.0.7 on 2024-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount', models.FloatField(default=60.0)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
    ]
